

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import HeaderBar from "@/components/HeaderBar";
import WindowStats from "@/components/WindowStats";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="z-20">
                    <HeaderBar></HeaderBar>
                </header>
                <div className="border-2 border-black">
                    {children}
                </div>
                <WindowStats />
            </body>
        </html>
    );
}
